sudo: required
services:
  - docker

before_install:
  - docker build -t hitbear/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hitbear/react-test yarn test --coverage

after_success:
  - docker build -t hitbear/multi-client ./client
  - docker build -t hitbear/multi-nginx ./nginx
  - docker build -t hitbear/multi-server ./server
  - docker build -t hitbear/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hitbear/multi-client
  - docker push hitbear/multi-nginx
  - docker push hitbear/multi-server
  - docker push hitbear/multi-worker
